# Changes here will be overwritten by Copier
_commit: 1.0.0-8-g1361223
_src_path: gh:DiamondLightSource/python-copier-template
author_email: giles.knap@diamond.ac.uk
author_name: Giles Knap
component_owner: user:hgv27681
description: A copier template for making epics-containers repositories for ioc and service instances
distribution_name: ec-services-template
docker: true
docs_type: README
git_platform: github.com
github_org: epics-containers
package_name: ioc_services_template
repo_name: ec-services-template
