# Changes here will be overwritten by Copier
_commit: 1.0.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: giles.knap@diamond.ac.uk
author_name: Giles Knap
component_owner: user:hgv27681
description: A copier template for making epics-containers domain services repositories
distribution_name: domain-services-template
docker: false
docs_type: README
git_platform: github.com
github_org: epics-containers
package_name: domain_services_template
repo_name: domain-services-template
