repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      # TODO can't get exclude to work - investigate
      # - id: check-yaml
      #   # exclude helm templates which are not valid yaml
      #   exclude: |
      #     templates/[^/].yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: Run black
        stages: [commit]
        language: system
        entry: black --check --diff
        types: [python]

      - id: ruff
        name: Run ruff
        stages: [commit]
        language: system
        entry: ruff
        types: [python]
