apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:

{{- $configPath := printf "services/%s/config/**" .Release.Name }}
# contents of the ioc instance config folder
{{ (.Files.Glob $configPath).AsConfig | indent 2 }}
