on:
  workflow_call:

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Prepare release files
        run: |
          if [ -d docs ]; then
            cd docs && zip -r docs.zip *
            echo 'DOCS=docs/docs.zip' >> $GITHUB_ENV
          fi
          if [ -d dist ]; then
            echo 'DIST=dist/*' >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # v0.1.15
        with:
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          files: |
            ${{ env.DOCS }}
            ${{ env.DIST }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
